### ISSUE TITLE
Weired error when deploying to Vercel

### ISSUE THREAD

**Issue by waylio** [andyrichardson/fielder#332]
Hey Andy,

I'm getting this error when deploying to Vercel. Its works perfectly on localhost and also works on another project in production. I'm not sure what is the problem here. 

Thanks in advance.

```
2022-07-30T17:05:23.242Z	c8ac1e5d-fa6e-494e-a5dc-6aeb3433a2f3	ERROR	TypeError: Cannot read properties of null (reading 'useRef')
    at Object.exports.useRef (/var/task/node_modules/fielder/node_modules/react/cjs/react.production.min.js:25:337)
    at exports.useForm (/var/task/node_modules/fielder/dist/index.js:1:5004)
    at Pay (/var/task/.next/server/pages/pay.js:111:67)
    at Hc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:13)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
2022-07-30T17:05:23.268Z	c8ac1e5d-fa6e-494e-a5dc-6aeb3433a2f3	ERROR	TypeError: Cannot read properties of null (reading 'useRef')
    at Object.exports.useRef (/var/task/node_modules/fielder/node_modules/react/cjs/react.production.min.js:25:337)
    at exports.useForm (/var/task/node_modules/fielder/dist/index.js:1:5004)
    at Pay (/var/task/.next/server/pages/pay.js:111:67)
    at Hc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:64:191)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:253)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:13)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89)
    at Kc (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:66:481)
    at Z (/var/task/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:89) {
  page: '/pay'
}
RequestId: c8ac1e5d-fa6e-494e-a5dc-6aeb3433a2f3 Error: Runtime exited with error: exit status 1
Runtime.ExitError


```

**Comment by andyrichardson** [comment]
Hey thanks for the report 👋

I know there were users successfully using this with SSR (#317) - any chance you can provide a reproduction so I can look into this?
